### ISSUE TITLE
HTML output image should always be within bounds

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/isodoc#71]
CSS rule should be set so that images/figures are always within bounds.

See below for an image going out of bounds.

<img width="648" alt="screen shot 2018-10-06 at 7 49 34 pm" src="https://user-images.githubusercontent.com/11865/46571074-1be96b80-c9a1-11e8-9183-ca2713b877e3.png">

**Comment by opoudjis** [comment]
There is already functionality that reduces the size of HTML images to fall within maximum bounds, in isodoc. Isodoc assumes that for HTML, `@maxwidth` = 1200 and ` @maxheight = 800`. Accordingly, the figure you are citing is being generated as `height="411" width="861"`.

.... But I see that the world has moved on, and the responsive thing to do is `img { width: 100%; height: auto;}`, instead of setting its height and width attributes proportionally within maximum bounds in isodoc.

... Yeah, OK.

**Comment by opoudjis** [comment]
As it turns out, CSS sizing overrides the inline image size parameters of images; so this is a pure CSS fix (for `@media screen`)

**Comment by opoudjis** [comment]
Fixed in stylesheets
