### ISSUE TITLE
Support pretty quotes

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/isodoc#80]
Currently our output do not support pretty quotes. Is this an isodoc thing or Metanorma-standoc? Or both?

**Comment by opoudjis** [comment]
One of the many problems with you constantly assigning more work is, you forget when work has already been assigned.

https://github.com/riboseinc/metanorma-standoc/issues/11 is a request to add smart quotes as an option to metanorma-standoc. This should not be left up to isodoc: smart quotes and dumb quotes are different character content, and the user should have control over when they appear (e.g. smart quotes, but citing content with dumb quotes). The user has a chance of controlling quote behaviour before the XML, because that's processing their input, including any overrides they put in to the input. The user should not trust a renderer like isodoc to make that decision for them.
