### ISSUE TITLE
URGENT FIX needed: "NOTE" is now "???" in Word and HTML

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/isodoc#85]
See ISO 8601-1 document. Urgent fix needed....

<img width="361" alt="screen shot 2019-01-29 at 5 00 23 pm" src="https://user-images.githubusercontent.com/11865/51896460-82c6e080-23e7-11e9-9b22-4c00d67a4025.png">

**Comment by ronaldtse** [comment]
FYI, the XML of a `<termnote>` in the ISO 8601-1 reads like below:

```xml
<termnote id="_935cc82c-431a-4a40-bf9b-8ff25be4fd63"> 
  <p id="_fdfce3af-e1f5-4d9b-b4d5-262742a5df0e">If <em>y</em> is omitted it is assumed to be zero. Thus [year(6)] means the same as [year(6,0)].</p> 
</termnote> 
```

**Comment by ronaldtse** [comment]
I see -- so these are `<termnote>`s inside definition lists! The normal term notes are fine.

**Comment by ronaldtse** [comment]
According to ISO/CS -- these are supposed to be normal "NOTE"s.

**Comment by ronaldtse** [comment]
i.e. `NOTE:` in `[nonterm]` sections are supposed to be normal "NOTE"s.

**Comment by opoudjis** [comment]
Termnotes are assigned labels in the places Metanorma expects to find termnotes: inside of terms. These termnotes are in clauses not terms (because [nonterm]), so they are not being assigned a label. The fix is to prevent termnotes from ever showing up in terms, as you have indicated: that is a cleanup operation within metanorma-standoc.

**Comment by ronaldtse** [comment]
Thank you @opoudjis !!!
